# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '/index.html'
    weight: 10
  - name: Experience
    url: '#journey'
    weight: 20
  - name: Software
    url: '#gallery'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Teaching
    url: '#tutorials'
    weight: 50
  - name: News
    url: '#news'
    weight: 60
